# Generated by Django 4.0.2 on 2022-02-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchedcity',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='searchedcity',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date and time'),
        ),
        migrations.AlterField(
            model_name='searchedcity',
            name='temperature',
            field=models.IntegerField(verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='searchedcity',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
        ),
    ]
